Blog/Blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('BlogApp.urls'), name = "BlogApp"),
    ]

Blog/BlogApp/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'BlogApp'

urlpatterns = [
        path('about/', views.AboutView.as_view() , name = "About"),
        path('', views.ArticleListView.as_view(), name="Article-List"),
        path('<int:pk>/', views.ArticleDetailView.as_view(), name="Article-Detail"),
        path('article/write/', views.ArticleCreateView.as_view(), name="Article-Create"),
        path('article/<int:pk>/edit/', views.ArticleUpdateView.as_view(), name="Article-Update"),
        path('article/<int:pk>/remove/', views.ArticleDeleteView.as_view(), name="Article-Delete"),
        path('drafts/', views.DraftListView.as_view(), name="Draft-List"),
        path('article/<int:pk>/comment/', views.add_comment_to_post, name="Comment-Add"),
        path('comment/<int:pk>/approve/', views.comment_approve, name="Comment-Approve"),
        path('comment/<int:pk>/remove/', views.comment_remove, name="Comment-Remove"),
        path('article/<int:pk>/publish/', views.article_publish, name="Article-Publish"),
        path('accounts/login/', LoginView.as_view(), name = 'login'),
        path('accounts/logout/', views.logout_view_func , name = 'logout'),
        ]

Blog/BlogApp/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone

class Article(models.Model):
    
    author = models.ForeignKey('auth.User', on_delete = models.CASCADE)
    title = models.CharField(max_length = 200)
    text = models.TextField()
    create_date = models.DateTimeField(default = timezone.now)
    published_date = models.DateTimeField(blank = True, null = True)

    def get_absolute_url(self):
        return reverse("BlogApp:Article-Detail", kwargs = {'pk': self.pk })

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def approve_comments(self):
        return self.comments.filter(approved_comment = True)

    def __str__(self):
        return self.title


class Comment(models.Model):

    article = models.ForeignKey(Article, related_name='comments', on_delete=models.CASCADE)
    author = models.CharField(max_length = 50)
    text = models.TextField()
    create_date = models.DateTimeField(default = timezone.now)
    approved_comment = models.BooleanField(default = False)

    def get_absolute_url(self):
        return reverse("BlogApp:Article-List")   

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

Blog/BlogApp/forms.py
from django import forms
from . import models

class ArticleForm(forms.ModelForm):
    
    class Meta():
        model = models.Article
        fields = ('author','title','text')

        widgets = {
                'title' : forms.TextInput(attrs ={'class' : 'textinputclass'}),
                'text' : forms.Textarea(attrs = {'class' : 'editable medium-editor-textarea postcontent'})
                }


class CommentForm(forms.ModelForm):

    class Meta():
        model = models.Comment
        fields = ('author','text')

        widgets = {
                'author' : forms.TextInput(attrs = {'class' : 'textinputclass'}),
                'text' : forms.Textarea(attrs = {'class' : 'editable medium-editor-textarea'})
                }

Blog/BlogApp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView,ListView, DetailView, CreateView, UpdateView, DeleteView
from . import models
from . import forms
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout

class AboutView(TemplateView):
    template_name = 'about.html'


class ArticleListView(ListView):
    template_name = 'BlogApp/article_list.html'
    
    def get_queryset(self):
        return models.Article.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')


class ArticleDetailView(DetailView):
    template_name = 'BlogApp/article_detail.html'
    
    def get_queryset(self):
        if not self.request.user.is_authenticated:
            return models.Article.objects.filter(published_date__lte=timezone.now())
        return models.Article.objects.all() 


class ArticleCreateView(LoginRequiredMixin, CreateView):
    login_url = '/accounts/login/'
    redirect_field_name = 'BlogApp/article_detail.html'

    template_name = 'BlogApp/article_create.html'
    form_class = forms.ArticleForm
    
    def get_queryset(self):
        return models.Article.objects.filter(author=self.request.user)


class ArticleUpdateView(LoginRequiredMixin, UpdateView):
    login_url = '/accounts/login/'
    redirect_field_name = 'BlogApp/article_detail.html'

    template_name = 'BlogApp/article_update.html'
    form_class = forms.ArticleForm
    
    def get_queryset(self):
        return models.Article.objects.filter(author=self.request.user)


class ArticleDeleteView(LoginRequiredMixin, DeleteView):
    login_url = '/accounts/login/'
    redirect_field_name = 'BlogApp/article_detail.html'

    template_name = 'BlogApp/article_delete.html'
    
    def get_queryset(self):
        return models.Article.objects.filter(author=self.request.user)

    def get_success_url(self):
        return reverse_lazy("BlogApp:Article-List")


class DraftListView(LoginRequiredMixin, ListView):
    login_url = '/accounts/login/'
    redirect_field_name = 'BlogApp/article_detail.html'

    template_name = 'BlogApp/article_list.html'

    def get_queryset(self):
        return  models.Article.objects.filter(author=self.request.user).filter(published_date__isnull=True).order_by('create_date')


@login_required
def article_publish(request, pk):
    article = get_object_or_404(models.Article, pk=pk)
    article.publish()
    return redirect('BlogApp:Article-Detail', pk=pk)


########   Comments   ########


def add_comment_to_post(request, pk):
    article = get_object_or_404(models.Article, pk=pk)
    if request.method == 'POST':
        form  = forms.CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit = False)
            comment.article = article
            comment.save()
            return redirect('BlogApp:Article-Detail', pk=pk)
    else:
        form = forms.CommentForm()
    return render(request, 'BlogApp/comment_form.html', {'form':form})

@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(models.Comment, pk=pk)
    comment.approve()
    return redirect('BlogApp:Article-Detail', pk=comment.article.pk)

@login_required
def comment_remove(request, pk):
    comment =  get_object_or_404(models.Comment, pk=pk)
    article_pk = comment.article.pk
    print(comment)
    print(comment.article)
    comment.delete()
    return redirect('BlogApp:Article-Detail', pk=article_pk)


########   LOGOUT   ########


@login_required
def logout_view_func(request):

    if request.method=="POST":
        logout(request)
        return redirect('BlogApp:Article-List')

    else :
        return render(request,"registration/logout.html",{})

Blog/BlogApp/templates/BlogApp/article_create.html
{% extends 'base.html' %}
	{% block content %}
	<br>
	<h1 class="techfont"> New Article </h1>
	<hr>
	<form class = "article-form" method="POST">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit" class="save btn btn-success">Save</button>
		<a href="{% url 'BlogApp:Article-List' %}" class="btn btn-secondary">Cancel</a>
	</form>

	<script>
		var editor = new MediumEditor('.editable');
	</script>
	{% endblock %}

Blog/BlogApp/templates/BlogApp/article_delete.html
{% extends 'base.html' %}
	{% block content %}
	<div class="jumbotron">
	<form method="POST">
		{% csrf_token %}
		<p><h3>Are you sure you want to delete "{{ object }}" ?</h3></p>
		<button type="submit" class="delete btn btn-danger">Yes, Delete</button>
		<a href="{% url 'BlogApp:Article-Detail' pk=object.pk %}" class="btn btn-secondary">Cancel</a>
	</form>
	</div>
	{% endblock %}

Blog/BlogApp/templates/BlogApp/article_detail.html
{% extends 'base.html' %}

	{% block content %}
	<br>
	<div class = "container article-main">
		<br>
		<h1 class="article-title hue">{{ object.title }}</h1>
		<div class="date article-date">
		{% if object.published_date %}
			{{ object.published_date }}
		{% else %}
			{{ object.create_date }}
		{% endif %}
		</div>
		<br>
		<div class="article-content">
		<p>{{ object.text|safe|linebreaksbr }}</p>
		<p class="article-date"><em>Written By : {{ object.author }}</em></p>
		</div>
		<br>
	</div>
		<br>
	{% if not object.published_date %}
		{% if user == object.author %}
		<a class="btn btn-success" href="{% url 'BlogApp:Article-Publish' pk=object.pk %}">Publish</a>
		{% endif %}
	{% endif %}
	{% if user == object.author %}
	<a class="btn btn-primary" href="{% url 'BlogApp:Article-Update' pk=object.pk %}"><img src="/static/icons/pencil.svg" alt="" class="side-icon"> Edit</a>
	<a class="btn btn-danger" href="{% url 'BlogApp:Article-Delete' pk=object.pk %}"><img src="/static/icons/x.svg" alt="" class="side-icon"> Delete</a>
	{% endif %}
	<br><br>
	<a class="btn btn-primary" href="{% url 'BlogApp:Comment-Add' pk=object.pk %}"><img src="/static/icons/comment.svg" alt="" class="side-icon"> Comment</a>
	<br><hr><br>
	<!-- Comments -->
	<h3><strong> Comments </strong></h3><br>
	<div class="container comments-section">
		{% for comment in object.comments.all %}
		<div class="comment-box">
		{% if user == object.author or comment.approved_comment %}
			{{ comment.create_date }}
			<p><strong>{{ comment.author }}</strong> commented</p>
			<p>{{ comment.text|safe|linebreaksbr }}</p>
			{% if not comment.approved_comment %}
			<div class="buttons">
				<a class="btn btn-success" href="{% url 'BlogApp:Comment-Approve' pk=comment.pk %}"><img src="/static/icons/pencil.svg" alt="" class="side-icon"> Approve</a>
				<a class="btn btn-danger" href="{% url 'BlogApp:Comment-Remove' pk=comment.pk %}"><img src="/static/icons/x.svg" alt="" class="side-icon"> Remove</a>
			</div>
			{% endif %}
			<hr>
		{% endif %}
		{% empty %}
		<h5>No Comments Yet</h5>
		</div>
		{% endfor %}
	</div>
	{% endblock %}

Blog/BlogApp/templates/BlogApp/article_list.html
{% extends 'base.html' %}
	{% block content %}

	<div class="centerstage">

		{% for article in object_list %}

		<div class="article">
			<h1 class="hue"><strong><a href="{% url 'BlogApp:Article-Detail' pk=article.pk %}">{{ article.title }}</a></strong></h1>
			<div class="date">
			{% if article.published_date %}
				<p>Published on : {{ article.published_date|date:"D, d M Y" }}</p>
			{% else %}
				<p>Created on : {{ article.create_date|date:"D, d M Y" }}</p>
			{% endif %}
			</div>
			<a href="{% url 'BlogApp:Article-Detail' pk=article.pk %}">Comments : {{ article.approve_comments.count }}</a>
			<hr>
		</div>

		{% endfor %}
		
	</div>

	{% endblock %}

Blog/BlogApp/templates/BlogApp/article_update.html
{% extends 'base.html' %}
	{% block content %}
	<br>
	<h1 class="techfont"> Update Article </h1>
	<hr>
	<form class = "article-form" method="POST">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit" class="save btn btn-success">Update</button>
		<a href="{% url 'BlogApp:Article-List' %}" class="btn btn-secondary">Cancel</a>
	</form>

	<script>
		var editor = new MediumEditor('.editable');
	</script>
	{% endblock %}

Blog/BlogApp/templates/BlogApp/comment_form.html
{% extends 'base.html' %}
	{% block content %}
	<br>
	<h1 class="techfont"> New Comment </h1>
	<hr>
	<form class="article-form" method="POST">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit" class="save btn btn-success">Post Comment</button>
		<a href="{% url 'BlogApp:Article-List' %}" class="btn btn-secondary">Cancel</a>
	</form>

	<script>
		var editor = new MediumEditor('.editable');
	</script>
	{% endblock %}

Blog/BlogApp/templates/about.html
{% extends 'base.html' %}
	{% block content %}
	<div class="jumbotron centerstage">
		<h1 class="techfont"> About The Site </h1>
		<p> Created by : Pratik Garai </p>
		<p> I am a Computer Science Engineering Student at VIT Chennai.</p>
	</div>
	{% endblock %}

Blog/BlogApp/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
	<head>

		<meta charset = "utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<title>Blog</title>
		
		<!-- JQuery -->
		<script src="/static/js/jquery.js"></script>

		<!-- Bootstrap -->
		<link rel="stylesheet" href="/static/css/bootstrap/bootstrap.css">
		<script src="/static/js/bootstrap/bootstrap.js"></script>
		
		<!-- Medium.com editor -->
		<link rel="stylesheet" href="/static/css/medium/medium-editor.css">
		<link rel="stylesheet" href="/static/css/medium/themes/default.css">
		<script src="/static/js/medium/medium-editor.js"></script>
		
		<!-- Custom CSS -->
		<link rel="stylesheet" href="/static/css/hue.css">
		<link rel="stylesheet" href="/static/css/blog.css">
		
		<!-- Fonts -->
		<link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Russo+One&display=swap" rel="stylesheet">

	</head>

	<body>
		<!-- Navbar -->
		<nav class="navbar navbar-light bg-light techfont custom-navbar">
			<div class="container">
				<ul class="nav navbar-nav">
					<li><a class="navbar-brand bigbrand hue" href="{% url 'BlogApp:Article-List' %}">My Blog</a></li>
					<li><a href="{% url 'BlogApp:About' %}">About</a></li>
					<li><a href="https://github.com/PratikGarai" target="_blank">GitHub</a></li>
					<li><a href="https://www.linkedin.com/in/pratik-garai-bab1a4191/" target="_blank">LinkedIn</a></li>
				</ul>

				<ul class="nav navbar-nav navbar-right">
					{% if user.is_authenticated %}
					<li><a href="{% url 'BlogApp:Article-Create' %}">New Article</a></li>
					<li><a href="{% url 'BlogApp:Draft-List' %}">Drafts</a></li>
					<li><a href="{% url 'BlogApp:logout' %}">Log Out</a></li>
					<li><a>Welcome : {{ user.username }}</a></li>
					{% else %}
					<li><a href="{% url 'BlogApp:login' %}"><img src="/static/icons/profile-fill.svg" alt="" class="side-icon"> Log In</a></li>
					{% endif %}
				</ul>
			</div>
		</nav>
		
		<!-- Main Body -->
		<div class="content container">
			<div class="row">
				<div class="col-sm-10">
					<div class="blog_posts">
						{% block content %}
						{% endblock %}
					</div>
				</div>
			</div>
		</div>
		<script>
			$(document).ready(function(){
				$('.article-form  div.medium-editor-textarea').addClass('article-textarea');
			});
		</script>	
	</body>
</html>

Blog/BlogApp/templates/navbar.html
<nav>
	<ul>
		<li><a href="#">Link 1</a></li>
		<li><a href="#">Link 2</a></li>
		<li><a href="#">Link 3</a></li>
		<li><a href="#">Link 4</a></li>
	</ul>
</nav>